apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: mukul0412/todo-aws-devops:v1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config

